# Generated by Django 4.2.9 on 2026-03-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('source_url', models.URLField(max_length=500, verbose_name='目标URL')),
                ('source_site', models.CharField(max_length=100, verbose_name='来源网站')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('items_crawled', models.IntegerField(default=0, verbose_name='抓取条目数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '爬虫任务',
                'verbose_name_plural': '爬虫任务',
                'db_table': 'crawler_crawltask',
                'ordering': ['-created_at'],
            },
        ),
    ]
