# Generated by Django 6.0.3 on 2026-03-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('base_url', models.URLField(max_length=500, verbose_name='基础URL')),
                ('list_url_pattern', models.CharField(blank=True, help_text='如: /ggzy/jyxx/001001/001001001/?page={page}', max_length=500, verbose_name='列表页URL模式')),
                ('selector_title', models.CharField(default='h1, .title, .article-title', max_length=200, verbose_name='标题选择器')),
                ('selector_content', models.CharField(default='.content, .article-content, .detail', max_length=200, verbose_name='内容选择器')),
                ('selector_publish_date', models.CharField(default='.publish-date, .time, .date', max_length=200, verbose_name='发布日期选择器')),
                ('selector_tenderer', models.CharField(default='.tenderer, .buyer, .purchaser', max_length=200, verbose_name='招标人选择器')),
                ('selector_budget', models.CharField(default='.budget, .amount, .price', max_length=200, verbose_name='预算金额选择器')),
                ('request_headers', models.JSONField(blank=True, default=dict, verbose_name='请求头配置')),
                ('request_cookies', models.JSONField(blank=True, default=dict, verbose_name='Cookie配置')),
                ('delay_seconds', models.IntegerField(default=1, help_text='每次请求之间的间隔时间', verbose_name='请求间隔(秒)')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用'), ('maintenance', '维护中')], default='active', max_length=20, verbose_name='状态')),
                ('last_crawl_at', models.DateTimeField(blank=True, null=True, verbose_name='最后爬取时间')),
                ('total_crawled', models.IntegerField(default=0, verbose_name='总爬取数')),
                ('success_rate', models.FloatField(default=100.0, verbose_name='成功率(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '爬虫源配置',
                'verbose_name_plural': '爬虫源配置',
                'db_table': 'crawler_sources',
                'ordering': ['-created_at'],
            },
        ),
    ]
