# Generated by Django 6.0.3 on 2026-03-26 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_crawlsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawltask',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_tasks', to='crawler.crawlsource', verbose_name='爬虫源'),
        ),
    ]
