# Generated by Django 4.2.9 on 2026-03-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_add_source_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlsource',
            name='api_field_budget',
            field=models.CharField(blank=True, help_text='预算金额的JSON路径', max_length=100, verbose_name='预算字段路径'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='api_field_date',
            field=models.CharField(blank=True, help_text='发布日期的JSON路径', max_length=100, verbose_name='日期字段路径'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='api_field_tenderer',
            field=models.CharField(blank=True, help_text='招标人/采购人的JSON路径', max_length=100, verbose_name='招标人字段路径'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='api_field_title',
            field=models.CharField(blank=True, help_text='如: title 或 data.title', max_length=100, verbose_name='标题字段路径'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='api_field_url',
            field=models.CharField(blank=True, help_text='详情页URL的JSON路径', max_length=100, verbose_name='URL字段路径'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='api_headers',
            field=models.JSONField(blank=True, default=dict, help_text='自定义请求头，如 {"Content-Type": "application/json"}', verbose_name='API请求头'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='api_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10, verbose_name='API请求方法'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='api_params',
            field=models.JSONField(blank=True, default=dict, help_text='JSON格式的请求参数，支持 {page} 占位符', verbose_name='API参数模板'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='api_response_path',
            field=models.CharField(blank=True, help_text='JSON路径，如: data.list 或 data.middle.listAndBox', max_length=200, verbose_name='响应数据路径'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='api_url',
            field=models.CharField(blank=True, help_text='如: https://api.example.com/search', max_length=500, verbose_name='API端点URL'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='extraction_mode',
            field=models.CharField(choices=[('html', 'HTML解析'), ('api', 'API调用'), ('intelligent', '智能提取'), ('llm', 'LLM提取'), ('auto', '自动选择最佳模式')], default='auto', help_text='选择数据提取方式，"自动选择"会依次尝试智能提取、LLM、HTML解析', max_length=20, verbose_name='数据提取模式'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='list_container_selector',
            field=models.CharField(blank=True, help_text='包含招标列表的容器，如: .list-container, #tender-list', max_length=200, verbose_name='列表容器选择器'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='list_item_selector',
            field=models.CharField(blank=True, help_text='每个招标条目的选择器，如: .list-item, tr.data-row', max_length=200, verbose_name='列表项选择器'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='list_link_selector',
            field=models.CharField(blank=True, help_text='从列表项中提取详情页链接的选择器，如: a.title, td:first-child a', max_length=200, verbose_name='详情链接选择器'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='max_pages',
            field=models.IntegerField(default=10, help_text='单次爬取的最大页数限制', verbose_name='最大爬取页数'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='page_param_name',
            field=models.CharField(default='page', help_text='API请求中的页码参数名', max_length=20, verbose_name='分页参数名'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='page_start',
            field=models.IntegerField(default=1, help_text='分页起始页码，通常为1', verbose_name='起始页码'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='use_javascript',
            field=models.BooleanField(default=False, help_text='开启后将使用Playwright渲染页面', verbose_name='需要JavaScript渲染'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='wait_for_selector',
            field=models.CharField(blank=True, help_text='等待此元素出现后再提取数据', max_length=200, verbose_name='等待元素选择器'),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='wait_timeout',
            field=models.IntegerField(default=5000, help_text='等待元素出现的最大时间', verbose_name='等待超时(毫秒)'),
        ),
    ]
