# Generated by Django 6.0.3 on 2026-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='额外权限'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('manager', '经理'), ('user', '普通用户'), ('viewer', '访客')], default='user', max_length=20, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='租户ID'),
        ),
    ]
