# Generated by Django 6.0.3 on 2026-03-25 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama (本地)'), ('openai', 'OpenAI'), ('claude', 'Claude (Anthropic)')], default='ollama', max_length=20, verbose_name='提供商')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='API密钥')),
                ('api_base_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='API基础URL')),
                ('model_name', models.CharField(default='qwen2.5:7b', max_length=100, verbose_name='模型名称')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('max_tokens', models.IntegerField(default=2000, verbose_name='最大Token数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'LLM配置',
                'verbose_name_plural': 'LLM配置',
                'db_table': 'llm_configs',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='对话标题')),
                ('messages', models.JSONField(default=list, verbose_name='消息记录')),
                ('tender_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联招标ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.llmconfig', verbose_name='使用的LLM配置')),
            ],
            options={
                'verbose_name': '对话记录',
                'verbose_name_plural': '对话记录',
                'db_table': 'llm_conversations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
