# Generated by Django 4.2.9 on 2026-03-26 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
