# Generated by Django 4.2 on 2024-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(db_index=True, max_length=200, verbose_name='关键词')),
                ('match_type', models.CharField(choices=[('exact', '精确匹配'), ('contains', '包含匹配'), ('starts_with', '开头匹配'), ('ends_with', '结尾匹配'), ('regex', '正则匹配')], default='contains', max_length=20, verbose_name='匹配类型')),
                ('case_sensitive', models.BooleanField(default=False, verbose_name='区分大小写')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='订阅名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('notify_email', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('notify_in_app', models.BooleanField(default=True, verbose_name='应用内通知')),
                ('notify_sms', models.BooleanField(default=False, verbose_name='短信通知')),
                ('frequency', models.CharField(choices=[('realtime', '实时'), ('hourly', '每小时'), ('daily', '每天')], default='daily', max_length=20, verbose_name='通知频率')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('max_keywords', models.IntegerField(default=50, verbose_name='最大关键词数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('user', models.ForeignKey('auth.User', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订阅',
                'verbose_name_plural': '订阅',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必需')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_subscriptions', to='subscriptions.keyword', verbose_name='关键词')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_keywords', to='subscriptions.subscription', verbose_name='订阅')),
            ],
            options={
                'verbose_name': '订阅关键词关联',
                'verbose_name_plural': '订阅关键词关联',
                'db_table': 'subscription_keywords',
                'unique_together': {('subscription', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(verbose_name='匹配分数')),
                ('matched_keywords', models.JSONField(default=list, verbose_name='匹配的关键词')),
                ('match_details', models.JSONField(default=dict, verbose_name='匹配详情')),
                ('is_notified', models.BooleanField(default=False, verbose_name='已通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_matches', to='tenders.tendernotice', verbose_name='招标机会')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='subscriptions.subscription', verbose_name='订阅')),
            ],
            options={
                'verbose_name': '匹配结果',
                'verbose_name_plural': '匹配结果',
                'db_table': 'match_results',
                'unique_together': {('subscription', 'opportunity')},
            },
        ),
    ]
