# Generated by Django 4.2 on 2024-01-01 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preferences', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='邮件通知启用')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='应用内通知启用')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='短信通知启用')),
                ('push_enabled', models.BooleanField(default=False, verbose_name='推送通知启用')),
                ('digest_mode', models.CharField(choices=[('realtime', '实时'), ('hourly', '每小时'), ('daily', '每日')], default='daily', max_length=20, verbose_name=' digest 模式')),
                ('digest_time', models.TimeField(default='09:00', verbose_name='digest 时间')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='免打扰开始时间')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='免打扰结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户通知偏好',
                'verbose_name_plural': '用户通知偏好',
                'db_table': 'user_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('email', '邮件'), ('in_app', '应用内'), ('sms', '短信'), ('push', '推送')], default='in_app', max_length=20, verbose_name='通知类型')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('delivered', '已送达'), ('read', '已读'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='主题')),
                ('content', models.TextField(verbose_name='内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('match_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='subscriptions.matchresult', verbose_name='匹配结果')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenders.tendernotice', verbose_name='招标机会')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='subscriptions.subscription', verbose_name='订阅')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
