# Generated by Django 4.2.9 on 2026-03-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenderNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notice_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='公告编号')),
                ('title', models.CharField(max_length=500, verbose_name='公告标题')),
                ('description', models.TextField(blank=True, verbose_name='公告描述')),
                ('tenderer', models.CharField(max_length=200, verbose_name='招标人')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='预算金额')),
                ('currency', models.CharField(choices=[('CNY', '人民币'), ('USD', '美元'), ('EUR', '欧元')], default='CNY', max_length=3, verbose_name='货币')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='发布日期')),
                ('deadline_date', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='地区')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='来源URL')),
                ('source_site', models.CharField(blank=True, max_length=100, verbose_name='来源网站')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('active', '进行中'), ('closed', '已关闭'), ('expired', '已过期')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI摘要')),
                ('ai_keywords', models.CharField(blank=True, max_length=500, verbose_name='AI关键词')),
                ('ai_category', models.CharField(blank=True, max_length=100, verbose_name='AI分类')),
                ('relevance_score', models.FloatField(blank=True, null=True, verbose_name='相关度评分')),
                ('crawl_batch_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='爬虫批次ID')),
            ],
            options={
                'verbose_name': '招标公告',
                'verbose_name_plural': '招标公告',
                'db_table': 'tender_notices',
                'ordering': ['-publish_date', '-created_at'],
                'indexes': [models.Index(fields=['title', 'publish_date'], name='tender_noti_title_5a3907_idx'), models.Index(fields=['tenderer', 'status'], name='tender_noti_tendere_dcd621_idx'), models.Index(fields=['region', 'industry'], name='tender_noti_region_56a17d_idx'), models.Index(fields=['crawl_batch_id', 'created_at'], name='tender_noti_crawl_b_671c52_idx')],
            },
        ),
    ]
