# Generated by Django 6.0.3 on 2026-03-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendernotice',
            name='budget_amount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=15, null=True, verbose_name='预算金额(标准化)'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='industry_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='行业编码'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='industry_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='行业名称'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='notice_type',
            field=models.CharField(choices=[('bidding', '招标公告'), ('win', '中标公告')], db_index=True, default='bidding', max_length=20, verbose_name='公告类型'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='project_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='地区编码'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='region_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='地区名称'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='search_vector',
            field=models.TextField(blank=True, null=True, verbose_name='搜索向量(SQLite)'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='winner',
            field=models.CharField(blank=True, max_length=200, verbose_name='中标人'),
        ),
        migrations.AlterField(
            model_name='tendernotice',
            name='publish_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发布日期'),
        ),
        migrations.AddIndex(
            model_name='tendernotice',
            index=models.Index(fields=['notice_type', 'publish_date'], name='tender_noti_notice__306bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='tendernotice',
            index=models.Index(fields=['region_code', 'industry_code'], name='tender_noti_region__c06434_idx'),
        ),
    ]
