# Generated by Django 6.0.3 on 2026-03-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tendernotice',
            new_name='tender_title_date_idx',
            old_name='tender_title_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='tendernotice',
            new_name='tenderer_status_idx',
            old_name='tender_tenderer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='tendernotice',
            new_name='region_industry_idx',
            old_name='tender_region_industry_idx',
        ),
        migrations.RenameIndex(
            model_name='tendernotice',
            new_name='region_code_idx',
            old_name='tender_region_codes_idx',
        ),
        migrations.RenameIndex(
            model_name='tendernotice',
            new_name='crawl_batch_idx',
            old_name='tender_crawl_batch_idx',
        ),
        migrations.RenameIndex(
            model_name='tendernotice',
            new_name='notice_type_date_idx',
            old_name='tender_notice_type_date_idx',
        ),
        migrations.RenameIndex(
            model_name='tendernotice',
            new_name='status_date_idx',
            old_name='tender_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='tendernotice',
            new_name='tenderer_date_idx',
            old_name='tender_tenderer_date_idx',
        ),
    ]
