# Generated by Django 6.0.3 on 2026-03-28 07:06

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_clean_html_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendernotice',
            name='delivery_period',
            field=models.CharField(blank=True, max_length=200, verbose_name='交付期限'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='evaluation_method',
            field=models.CharField(blank=True, max_length=200, verbose_name='评标方法'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='extraction_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='提取置信度'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='extraction_method',
            field=models.CharField(blank=True, default='unknown', max_length=50, verbose_name='提取方法'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='main_pdf_content',
            field=models.TextField(blank=True, verbose_name='PDF正文内容'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='main_pdf_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='PDF原文URL'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='payment_terms',
            field=models.TextField(blank=True, verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='qualification_requirements',
            field=models.TextField(blank=True, verbose_name='投标人资格要求'),
        ),
        migrations.AddField(
            model_name='tendernotice',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=200, verbose_name='质保期'),
        ),
        migrations.AlterField(
            model_name='tendernotice',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='搜索向量'),
        ),
        migrations.CreateModel(
            name='TenderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物品名称')),
                ('specification', models.TextField(blank=True, verbose_name='规格型号')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='物品类别/品目')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='数量')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='单位')),
                ('budget_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='预算单价')),
                ('budget_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='预算总价')),
                ('technical_requirements', models.TextField(blank=True, verbose_name='技术要求/参数')),
                ('delivery_requirements', models.TextField(blank=True, verbose_name='交付要求')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tender_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenders.tendernotice', verbose_name='关联招标公告')),
            ],
            options={
                'verbose_name': '采购物品',
                'verbose_name_plural': '采购物品',
                'db_table': 'tender_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TenderTechnicalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='参数名称')),
                ('value', models.TextField(verbose_name='参数值/要求')),
                ('category', models.CharField(blank=True, help_text='如：性能指标、功能要求、物理规格等', max_length=50, verbose_name='参数类别')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='是否必须满足')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tender_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_parameters', to='tenders.tendernotice', verbose_name='关联招标公告')),
            ],
            options={
                'verbose_name': '技术参数',
                'verbose_name_plural': '技术参数',
                'db_table': 'tender_technical_parameters',
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
    ]
